### ISSUE TITLE
totally_real_apk.apk screwing up continuous deployment file filters

### ISSUE THREAD

**Issue by jpike88** [angular/webdriver-js-extender#14]
The file totally_real_apk.apk has caused grief for me using bitrise, because the apk post-build fetch raises a false positive on this filename.

I'd highly recommend not naming anything .apk unless it's an actual apk, that took me hours to figure out.

Thanks

**Comment by jpike88** [comment]
![screen shot 2017-05-14 at 3 02 15 pm](https://cloud.githubusercontent.com/assets/9585787/26031430/5d5c0618-38b6-11e7-8e61-2b397e452f5f.png)

**Comment by NickTomlin** [comment]
I believe these are test files or artifacts created from testing. Is bitrise scanning `node_modules`? It seems reasonable to ignore these paths in whatever CI solution you are using. 

@sjelin i'm very foggy on the use case besides being generically android related; do you have any thoughts here?

**Comment by Jacob-McKay** [comment]
Had **/*.apk in my publish to MS app center, build started failing when we added this node_module.  I agree if your npm package doesn't need this file or if it can be renamed that you should change/remove it.

While this issue is inconvenient and can lead to wasted CI/CD troubleshooting time, there is an obvious workaround of being more specific which apk you are publishing, in the case of my ionic app that's: platforms/android/build/outputs/apk/android-release.apk

**Comment by kyliau** [comment]
This issue has been fixed in v2.2.0 release.
