### ISSUE TITLE
Crazy nested `built` directories

### ISSUE THREAD

**Issue by MatthewMarichiba** [angular/webdriver-js-extender#29]
I am reporting this on a "code smell" only. While exploring webdriver, chromedriver, and related dependencies for my Angular project's CI needs, I discovered a crazy "Christmas Tree" of nested `built` directories under my `node_modules` directory. (See below.) I don't know what causes it, but each `built` directory appears to contain a single file `totally_real_apk.apk` with no contents. 

Is something going haywire with the webdriver-js-extender build process?

![image](https://user-images.githubusercontent.com/967541/56438733-cb7c9000-6298-11e9-9740-4d46d7132df7.png)

This is not causing problems for us as far as I can tell. Thanks for all you do!

**Comment by Vikki123** [comment]
This is a problem for us in our project. Visual studio is crashing as the max path limit is 260 characters.

**Comment by toybcm2** [comment]
This is also causing publishing issue on one of our projects due to max path length

**Comment by Shoe2** [comment]
have this path too

**Comment by muralikvp** [comment]
It is causing the long path issue for my project as well. Git is throwing the below error due to this multiple folders. Manually removing the Folders. Any one find the solution for this problem ?

Git stated the below eror
"The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
"

**Comment by tudorsibiu90** [comment]
We also experience this problem.

**Comment by jpeg729** [comment]
Just got bit by this. Our jenkins build failed because the filename was too long.

**Comment by kyliau** [comment]
This issue has been fixed in v2.2.0 release.

**Comment by 0988jaylin** [comment]
> This issue has been fixed in v2.2.0 release.

May I know which application/component's v2.2.0 release? thanks.
